postgres:
  image: postgres:9.3
  environment:
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_USER: postgres
redis:
  image: redis
elasticsearch:
  image: elasticsearch
web:
  build: .
  volumes:
    - ./:/opt/hummingbird/
  ports:
    - 3000:3000
    - 4200
    - 49152:49152
  links:
    - postgres
    - redis
    - elasticsearch
  environment:
    RAILS_ENV: development

